// <auto-generated />
using ContaBancoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContaBancoApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230811224809_agenciaFK")]
    partial class agenciaFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ContaBancoApi.Entidades.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Saldo")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("agencias");
                });

            modelBuilder.Entity("ContaBancoApi.Entidades.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgenciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumConta")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Saldo")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("contasBancarias");
                });

            modelBuilder.Entity("ContaBancoApi.Entidades.ContaBancaria", b =>
                {
                    b.HasOne("ContaBancoApi.Entidades.Agencia", "Agencia")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("ContaBancoApi.Entidades.Agencia", b =>
                {
                    b.Navigation("ContasBancarias");
                });
#pragma warning restore 612, 618
        }
    }
}
